"""Generate long, non-repetitive prompts for TTFT experiments.

Each prompt is a concatenation of distinct sentences so that token count can
be controlled without using silly repeated words like "Hi" / "Hey".
"""

import random

_SENTENCE_POOL = [
    "The rapid advancement of artificial intelligence has transformed many industries in recent years.",
    "Large language models can now generate coherent text, translate between languages, and answer complex questions.",
    "Machine learning systems require vast amounts of data and significant computational resources for training.",
    "Researchers continue to explore new architectures that improve both efficiency and accuracy.",
    "Natural language processing has become a cornerstone of modern AI applications.",
    "Deep neural networks are inspired by the structure and function of the human brain.",
    "Training state-of-the-art models often involves thousands of GPUs running for weeks or months.",
    "The development of transformers revolutionized sequence modeling across many domains.",
    "Attention mechanisms allow models to focus on the most relevant parts of the input.",
    "Fine-tuning pretrained models on domain-specific data can yield impressive results with limited labels.",
    "Reinforcement learning from human feedback has become a popular technique for aligning language models.",
    "Multimodal models can process text, images, audio, and video within a single architecture.",
    "Model compression techniques such as quantization and pruning help deploy models on resource-constrained devices.",
    "The evaluation of generative models remains challenging due to the subjective nature of quality.",
    "Bias and safety are critical concerns when deploying language models in real-world applications.",
    "Open-source models have accelerated research by making powerful tools accessible to the broader community.",
    "Cloud providers offer specialized accelerators designed specifically for deep learning workloads.",
    "Distributed training frameworks help scale model training across clusters of machines.",
    "Data privacy regulations influence how training data can be collected and used.",
    "Prompt engineering has emerged as a practical skill for getting the best out of language models.",
    "Chain-of-thought prompting can improve reasoning performance on complex tasks.",
    "Retrieval-augmented generation combines parametric knowledge with external information sources.",
    "Vector databases enable efficient similarity search over large document collections.",
    "Tokenization strategies affect model vocabulary, latency, and multilingual capabilities.",
    "Subword algorithms like Byte Pair Encoding balance vocabulary size and sequence length.",
    "Long-context models can process documents that are tens of thousands of tokens long.",
    "Positional encoding schemes help transformers understand token order in sequences.",
    "Mixture-of-experts architectures increase model capacity without proportional compute growth.",
    "Speculative decoding reduces latency by using a smaller draft model to propose tokens.",
    "Continuous batching improves serving throughput by dynamically packing requests.",
    "KV cache management is essential for efficient autoregressive generation.",
    "PagedAttention reduces memory fragmentation when serving many concurrent requests.",
    "Disaggregating prefill and decode can improve resource utilization in serving clusters.",
    "Prefill-heavy workloads benefit from high-throughput batch processing.",
    "Decode-heavy workloads require low-latency single-token generation.",
    "Request scheduling policies affect tail latency and fairness in serving systems.",
    "Dynamic batching must balance throughput against time-to-first-token constraints.",
    "Tensor parallelism splits model weights across multiple GPUs within a single node.",
    "Pipeline parallelism assigns consecutive layers to different devices.",
    "Data parallelism replicates models across workers to scale batch size.",
    "Sequence parallelism distributes attention computation across devices.",
    "Gradient checkpointing trades compute for memory during training.",
    "ZeRO-style optimizers partition optimizer states across data-parallel workers.",
    "Communication overhead can dominate training time at large scales.",
    "High-bandwidth interconnects such as NVLink and InfiniBand reduce communication bottlenecks.",
    "Model serving systems must handle variable input lengths and output lengths.",
    "Batching requests with similar lengths improves hardware utilization.",
    "Early stopping and length penalties help control generation quality.",
    "Temperature and top-p sampling introduce diversity into generated text.",
    "Beam search explores multiple candidate sequences before selecting the best one.",
    "Logit processors can enforce constraints such as repetition penalties or banned phrases.",
    "Structured generation ensures outputs conform to schemas or grammars.",
    "Agentic systems combine language models with tools and external APIs.",
    "Tool use requires the model to understand when and how to invoke external functions.",
    "Memory-augmented architectures can retain information across long conversations.",
    "Evaluating agent performance involves both correctness and efficiency metrics.",
    "Hallucination remains a major challenge for factual applications of language models.",
    "Attribution techniques help trace generated statements back to source documents.",
    "Adversarial testing probes model robustness against misleading inputs.",
    "Interpretability research seeks to understand the internal representations of neural networks.",
    "Mechanistic interpretability attempts to reverse-engineer circuits inside models.",
    "Probing classifiers reveal what kinds of information are encoded in hidden states.",
    "Feature visualization techniques highlight input patterns that activate specific neurons.",
    "Red-teaming exercises identify harmful capabilities before deployment.",
    "Constitutional AI trains models using a set of principles rather than direct human labels.",
    "Federated learning enables training on decentralized data without centralizing sensitive information.",
    "Differential privacy provides mathematical guarantees for data confidentiality.",
    "On-device inference brings AI capabilities to smartphones and edge devices.",
    "Neural architecture search automates the design of efficient model structures.",
    "Knowledge distillation transfers capabilities from large teacher models to smaller students.",
    "Self-supervised learning leverages unlabeled data to learn useful representations.",
    "Contrastive learning learns embeddings by pulling similar samples together and pushing dissimilar ones apart.",
    "Masked language modeling predicts missing tokens from context.",
    "Causal language modeling predicts the next token given all previous tokens.",
    "Permutation language modeling generalizes left-to-right and right-to-left objectives.",
    "Sparse attention patterns reduce the quadratic cost of full self-attention.",
    "Linear attention mechanisms approximate softmax attention with cheaper kernels.",
    "State space models offer an alternative to transformers for long sequences.",
    "Mamba architectures combine recurrent and convolutional inductive biases.",
    "Structured state spaces enable efficient training and inference on very long inputs.",
    "Neural Turing machines augment networks with external read-write memory.",
    "Differentiable neural computers use attention to read from and write to a memory matrix.",
    "Graph neural networks operate on relational data represented as nodes and edges.",
    "Geometric deep learning generalizes neural networks to non-Euclidean domains.",
    "Equivariant neural networks respect symmetries such as rotations and translations.",
    "Bayesian neural networks quantify uncertainty in predictions.",
    "Neural processes define distributions over functions given context points.",
    "Meta-learning algorithms learn how to learn from few examples.",
    "Few-shot prompting demonstrates tasks through examples rather than fine-tuning.",
    "Zero-shot prompting relies on the model's pre-trained knowledge to perform tasks.",
    "Instruction tuning improves model ability to follow natural language commands.",
    "Chat templates format conversations so models can distinguish user and assistant turns.",
    "System prompts set the behavior and constraints of an assistant.",
    "Context windows limit how much information a model can attend to at once.",
    "Sliding window attention extends effective context with local attention patterns.",
    "Ring attention enables context lengths that exceed a single accelerator's memory.",
    "Memory-efficient attention algorithms reduce the storage cost of attention scores.",
    "FlashAttention computes attention in a way that is IO-aware and tiling-friendly.",
    "Kernel fusion reduces launch overhead by combining multiple operations into one.",
    "CUDA graphs reduce CPU overhead by capturing and replaying kernel sequences.",
    "Triton kernels allow custom GPU kernels to be written in Python-like syntax.",
    "Dynamic shape handling complicates kernel optimization for variable-length sequences.",
    "Compilation frameworks trace and optimize model execution graphs.",
    "Operator fusion rewrites multiple consecutive operations into a single kernel.",
    "Memory planning pre-allocates buffers to avoid runtime allocation overhead.",
    "Weight sharing reduces model size by reusing parameters across layers.",
    "Low-rank adaptation adds small trainable matrices to frozen pretrained weights.",
    "Prefix tuning prepends trainable vectors to each layer's activations.",
    "Adapter layers insert bottleneck modules between transformer sublayers.",
    "Instruction datasets are curated to teach models to follow diverse commands.",
    "Preference datasets capture human judgments between model outputs.",
    "Synthetic data generation can augment training sets for specific capabilities.",
    "Data cleaning removes noise and duplicates that harm model performance.",
    "Deduplication prevents the model from memorizing repeated training examples.",
    "Quality filtering selects high-quality documents from large web corpora.",
    "Mixture-of-tokens training samples tokens from multiple documents per update.",
    "Curriculum learning presents examples in order of increasing difficulty.",
    "Active learning selects the most informative unlabeled examples for annotation.",
    "Weak supervision uses noisy labels from heuristics or distant supervision.",
    "Semi-supervised learning combines limited labeled data with abundant unlabeled data.",
    "Self-improvement methods generate new training data from the model itself.",
    "Rejection sampling filters generated examples by quality or correctness.",
    "Verifier models score and filter candidate reasoning traces.",
    "Process reward models provide feedback on intermediate reasoning steps.",
    "Outcome reward models judge the final result of a reasoning chain.",
    "Monte Carlo tree search can be used for planning in language model agents.",
    "Tool-learning benchmarks evaluate model ability to use calculators, search engines, and APIs.",
    "Multilingual models are trained on text from dozens or hundreds of languages.",
    "Code generation models are trained on large repositories of source code.",
    "Execution-based evaluation tests code by running it against test cases.",
    "Unit-test generation is an emerging capability for automated software testing.",
    "Docstring generation helps maintain software documentation automatically.",
    "Bug localization models identify which code changes introduced defects.",
    "Patch generation systems suggest fixes for identified vulnerabilities.",
    "Scientific discovery applications use language models to summarize literature and propose hypotheses.",
    "Medical question answering requires high factual accuracy and careful safety review.",
    "Legal document analysis benefits from long-context and retrieval capabilities.",
    "Financial forecasting applications combine text, numbers, and time-series data.",
    "Educational tutoring systems adapt explanations to individual student needs.",
    "Accessibility tools use speech recognition and synthesis to assist users.",
    "Creative writing assistants help authors brainstorm and revise drafts.",
    "Game development uses procedural content generation to create quests and dialogues.",
    "Dialogue systems maintain coherent multi-turn conversations with users.",
    "Emotion recognition from text can improve conversational AI responses.",
    "Personalization systems tailor recommendations based on user history and preferences.",
    "Search engines increasingly use neural reranking to improve result quality.",
    "Question answering systems combine retrieval and generation to produce grounded answers.",
    "Summarization models condense long documents into shorter, informative versions.",
    "Translation models must preserve meaning while adapting to target language style.",
    "Paraphrasing systems rephrase text while maintaining semantic equivalence.",
    "Text simplification makes complex content accessible to broader audiences.",
    "Style transfer rewrites text to match a desired tone or authorial voice.",
    "Named entity recognition identifies people, organizations, and locations in text.",
    "Relation extraction determines semantic relationships between entities.",
    "Coreference resolution links pronouns and mentions to the same real-world entities.",
    "Semantic parsing converts natural language into formal meaning representations.",
    "Textual entailment judges whether one sentence implies, contradicts, or is neutral to another.",
    "Sentiment analysis classifies opinions expressed in text as positive, negative, or neutral.",
    "Topic modeling discovers latent themes in large document collections.",
    "Clustering algorithms group similar documents or sentences together.",
    "Dimensionality reduction techniques visualize high-dimensional text embeddings.",
    "Anomaly detection identifies unusual patterns in text streams.",
    "Temporal analysis tracks how language use and topics evolve over time.",
    "Cross-lingual transfer enables models trained on one language to help others.",
    "Linguistic typology studies structural variation across the world's languages.",
    "Morphological analysis breaks words into stems, prefixes, and suffixes.",
    "Part-of-speech tagging labels each word with its grammatical category.",
    "Dependency parsing reveals grammatical relationships between words in a sentence.",
    "Constituency parsing represents sentence structure as nested phrases.",
    "Semantic role labeling identifies who did what to whom in an event.",
    "Discourse parsing models the rhetorical structure of multi-sentence texts.",
    "Coherence modeling evaluates whether a sequence of sentences forms a coherent passage.",
    "Readability metrics estimate the difficulty of a text for human readers.",
    "Stylometry analyzes writing style to attribute authorship or detect plagiarism.",
    "Forensic linguistics applies language analysis to legal investigations.",
    "Computational psycholinguistics models human language processing.",
    "Neurolinguistics studies how the brain represents and processes language.",
    "Historical linguistics uses computational methods to trace language change.",
    "Sociolinguistics examines how language varies across social groups and contexts.",
    "Pragmatics concerns how context affects interpretation of meaning.",
    "Speech processing converts spoken language into text and vice versa.",
    "Speaker diarization determines who spoke when in an audio recording.",
    "Text-to-speech synthesis generates natural-sounding speech from written text.",
    "Automatic speech recognition maps acoustic signals to word sequences.",
    "Voice conversion transforms one speaker's voice to sound like another.",
    "Music generation models compose melodies, harmonies, and rhythms.",
    "Image generation systems create photorealistic or artistic images from text descriptions.",
    "Video generation extends image generation to produce coherent motion sequences.",
    "Diffusion models generate data by reversing a gradual noise corruption process.",
    "Generative adversarial networks train a generator against a discriminator.",
    "Normalizing flows model complex distributions through invertible transformations.",
    "Variational autoencoders learn compact latent representations of data.",
    "Energy-based models assign scores to data configurations.",
    "Autoregressive models generate sequences one element at a time.",
    "Non-autoregressive generation aims to reduce latency by predicting in parallel.",
    "Semi-autoregressive methods strike a balance between speed and quality.",
    "Consistency models learn to map noise directly to data in a single step.",
    "Flow matching provides a flexible framework for generative modeling.",
    "Score-based models estimate gradients of the data distribution.",
    "Latent diffusion models operate in a compressed representation space.",
    "Text-conditioned image generation maps captions to visual content.",
    "Inpainting fills in missing regions of an image based on context.",
    "Super-resolution increases image resolution while preserving detail.",
    "Neural radiance fields represent 3D scenes from 2D images.",
    "Gaussian splatting renders 3D scenes using point-based representations.",
    "Robotics foundation models learn generalizable manipulation skills.",
    "Embodied AI agents perceive and act within simulated or real environments.",
    "Sim-to-real transfer bridges the gap between simulation and physical deployment.",
    "World models learn predictive representations of environment dynamics.",
    "Reinforcement learning agents learn policies through trial and error.",
    "Model-based planning uses learned dynamics to search for optimal actions.",
    "Imitation learning clones expert behavior from demonstrations.",
    "Inverse reinforcement learning infers reward functions from observed behavior.",
    "Multi-agent systems study interaction and coordination among autonomous agents.",
    "Game theory provides tools for analyzing strategic agent interactions.",
    "Mechanism design aligns individual incentives with collective outcomes.",
    "Causal inference distinguishes correlation from causation.",
    "Causal discovery algorithms infer causal graphs from observational data.",
    "Treatment effect estimation measures the impact of interventions.",
    "Counterfactual reasoning imagines alternative scenarios and outcomes.",
    "Uncertainty quantification communicates confidence in predictions.",
    "Calibration ensures that predicted probabilities match observed frequencies.",
    "Fairness metrics evaluate whether models treat groups equitably.",
    "Explainable AI produces human-understandable justifications for predictions.",
    "Local explanations describe why a model made a specific decision.",
    "Global explanations summarize overall model behavior across inputs.",
    "Concept-based explanations link predictions to human-understandable concepts.",
    "Provenance tracking records the data and computations behind decisions.",
    "Responsible AI development considers societal impact alongside technical progress.",
    "The future of AI depends on building systems that are safe, beneficial, and broadly accessible.",
]


def generate_prompts(num_prompts: int = 4, target_chars: int = 16000, seed: int = 42) -> list[str]:
    """Generate a list of long, non-repetitive prompts.

    Each prompt is guaranteed to have at least `target_chars` characters.
    A rough rule of thumb for Qwen tokenizer is ~4 characters per token,
    so 16000 characters corresponds to approximately 4000 tokens.
    """
    rng = random.Random(seed)
    pool = _SENTENCE_POOL[:]
    prompts = []
    for i in range(num_prompts):
        rng.shuffle(pool)
        parts = []
        chars = 0
        idx = 0
        while chars < target_chars:
            sentence = pool[idx % len(pool)]
            parts.append(sentence)
            chars += len(sentence) + 1  # +1 for the space
            idx += 1
        prompts.append(" ".join(parts))
    return prompts


if __name__ == "__main__":
    ps = generate_prompts()
    for i, p in enumerate(ps):
        print(f"Prompt {i}: {len(p)} chars")
